NoPrecin/Controllers/ProdutosController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using NoPrecin.Context;
using NoPrecin.Models;

namespace NoPrecin.Controllers
{
    public class ProdutosController : Controller
    {
        private readonly string apiUrl = "https://localhost:44328/api/produtos/";
        private readonly string apiUrlv = "https://localhost:44328/api/vendas/";

        //Define uma instância de IHostingEnvironment
        IWebHostEnvironment _appEnvironment;
        private readonly AppDbContext _context;
        //Injeta a instância no construtor para poder usar os recursos
        public ProdutosController(IWebHostEnvironment env, AppDbContext context)
        {
            _appEnvironment = env;
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            List<Produtos> listaProdutos = new List<Produtos>();

            Usuario usuario = new Usuario();
            usuario.Id = HttpContext.Session.Get<Guid>("Id");
            usuario.AcessToken = HttpContext.Session.Get<String>("AcessToken");
            usuario.Email = HttpContext.Session.Get<String>("Email");

            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(apiUrl))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    listaProdutos = JsonConvert.DeserializeObject<List<Produtos>>(apiResponse);
                }
            }

            return View(listaProdutos.Where(x => x.Ativo == true));
        }

        public IActionResult Criar()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Criar(Produtos produto, IFormFile arquivo)
        {
            Guid guid = Guid.NewGuid();
            Guid idImagem = Guid.NewGuid();

            Usuario usuario = new Usuario();
            usuario.Id = HttpContext.Session.Get<Guid>("Id");
            usuario.AcessToken = HttpContext.Session.Get<String>("AcessToken");
            usuario.Email = HttpContext.Session.Get<String>("Email");

            // Define um nome para o arquivo enviado incluindo o sufixo obtido de milesegundos
            string nomeArquivo = guid.ToString();

            if (arquivo != null)
            {
                //verifica qual o tipo de arquivo : jpg, gif, png, pdf ou tmp
                if (arquivo.FileName.Contains(".jpg"))
                    nomeArquivo += ".jpg";
                else if (arquivo.FileName.Contains(".gif"))
                    nomeArquivo += ".gif";
                else if (arquivo.FileName.Contains(".png"))
                    nomeArquivo += ".png";
                else if (arquivo.FileName.Contains(".pdf"))
                    nomeArquivo += ".pdf";
                else
                    nomeArquivo += ".tmp";

                //< obtém o caminho físico da pasta wwwroot >
                string caminho_WebRoot = _appEnvironment.WebRootPath;
                // monta o caminho onde vamos salvar o arquivo :  ~\wwwroot\Arquivos\Arquivos_Usuario\Recebidos
                string caminhoDestinoArquivo = caminho_WebRoot + "\\img\\";

                // incluir a pasta Recebidos e o nome do arquiov enviado : ~\wwwroot\Arquivos\Arquivos_Usuario\Recebidos\
                string caminhoDestinoArquivoOriginal = caminhoDestinoArquivo + nomeArquivo;

                //copia o arquivo para o local de destino original
                using (var stream = new FileStream(caminhoDestinoArquivoOriginal, FileMode.Create))
                {
                    await arquivo.CopyToAsync(stream);
                }
            }

            produto.Id = idImagem;
            produto.EmailProprietario = usuario.Email;
            produto.DataCadastro = DateTime.Now;
            produto.Imagem = nomeArquivo;

            //TODO: Acesso direto ao banco de dados
            //_context.Add(produto);
            //await _context.SaveChangesAsync();

            //TODO: Acesso API
            var json = JsonConvert.SerializeObject(produto);
            var postRequest = new StringContent(json, Encoding.UTF8, "application/json");

            using (var httpClient = new HttpClient())
            {
                httpClient.DefaultRequestHeaders.Add("Authorization", "Bearer " + usuario.AcessToken);

                using (var response = await httpClient.PostAsync(apiUrl, postRequest).ConfigureAwait(false))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    produto = JsonConvert.DeserializeObject<Produtos>(apiResponse);
                }
            }

            return RedirectToAction("ListarPorUsuario", "Produtos");
        }

        public async Task<IActionResult> Editar(Guid id)
        {
            Produtos produtos = new Produtos();
            Usuario usuario = new Usuario();
            usuario.Id = HttpContext.Session.Get<Guid>("Id");
            usuario.AcessToken = HttpContext.Session.Get<String>("AcessToken");
            usuario.Email = HttpContext.Session.Get<String>("Email");

            using (var httpClient = new HttpClient())
            {
                httpClient.DefaultRequestHeaders.Add("Authorization", "Bearer " + usuario.AcessToken);

                using (var response = await httpClient.GetAsync(apiUrl + id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    produtos = JsonConvert.DeserializeObject<Produtos>(apiResponse);
                }
            }
            return View(produtos);
        }

        [HttpPost]
        public async Task<IActionResult> Editar(int id, Produtos produto)
        {
            Usuario usuario = new Usuario();
            usuario.AcessToken = HttpContext.Session.Get<String>("AcessToken");
            produto.EmailProprietario = HttpContext.Session.Get<String>("Email");

            //TODO: Acesso banco de dados
            //_context.Update(produto);
            //await _context.SaveChangesAsync();

            //TODO: Acesso API
            var json = JsonConvert.SerializeObject(produto);
            var postRequest = new StringContent(json, Encoding.UTF8, "application/json");

            using (var httpClient = new HttpClient())
            {
                httpClient.DefaultRequestHeaders.Add("Authorization", "Bearer " + usuario.AcessToken);

                using (var response = await httpClient.PutAsync(apiUrl + produto.Id, postRequest))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                }
            }

            return RedirectToAction("ListarPorUsuario", "Produtos");
        }

        public async Task<IActionResult> Deletar(Guid id)
        {
            Usuario usuario = new Usuario();
            usuario.AcessToken = HttpContext.Session.Get<String>("AcessToken");

            using (var httpClient = new HttpClient())
            {
                httpClient.DefaultRequestHeaders.Add("Authorization", "Bearer " + usuario.AcessToken);

                await httpClient.DeleteAsync(apiUrl + id);
            }

            return RedirectToAction("ListarPorUsuario", "Produtos");
        }


        public async Task<IActionResult> ListarPorUsuario()
        {
            List<Produtos> listaProdutos = new List<Produtos>();

            Usuario usuario = new Usuario();
            usuario.Id = HttpContext.Session.Get<Guid>("Id");
            usuario.AcessToken = HttpContext.Session.Get<String>("AcessToken");
            usuario.Email = HttpContext.Session.Get<String>("Email");
            //Retorna para a viu todos os produtos
            if (usuario.AcessToken == null)
            {
                return RedirectToAction("Login", "Usuarios");
            }

            using (var httpClient = new HttpClient())
            {
                httpClient.DefaultRequestHeaders.Add("Authorization", "Bearer " + usuario.AcessToken);

                using (var response = await httpClient.GetAsync(apiUrl + "por-usuario/" + usuario.Id))
                {

                    string apiResponse = await response.Content.ReadAsStringAsync();
                    listaProdutos = JsonConvert.DeserializeObject<List<Produtos>>(apiResponse);
                }
            }

            //Se o usuário estiver logado retorna lista com seus produtos
            return View(listaProdutos);
        }

        public async Task<IActionResult> MinhasCompras()
        {
            List<Vendas> listarVendas = new List<Vendas>();
            List<Vendas> lista = new List<Vendas>();

            Usuario usuario = new Usuario();
            usuario.Id = HttpContext.Session.Get<Guid>("Id");
            usuario.AcessToken = HttpContext.Session.Get<String>("AcessToken");
            usuario.Email = HttpContext.Session.Get<String>("Email");
            //Retorna para a viu todos os produtos
            if (usuario.AcessToken == null)
            {
                return RedirectToAction("Login", "Usuarios");
            }

            using (var httpClient = new HttpClient())
            {
                httpClient.DefaultRequestHeaders.Add("Authorization", "Bearer " + usuario.AcessToken);

                using (var response = await httpClient.GetAsync(apiUrlv))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();

                    lista = JsonConvert.DeserializeObject<List<Vendas>>(apiResponse);
                }
            }

            foreach (var item in lista)
            {
                if (item.EmailComprador == usuario.Email)

NoPrecin/Controllers/VendasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using NoPrecin.Models;

namespace NoPrecin.Controllers
{
    public class VendasController : Controller
    {
        /*public IActionResult Index()
        {
            return View();
        }*/

        private readonly string apiUrlv = "https://localhost:44328/api/vendas";
        private readonly string apiUrl = "https://localhost:44328/api/produtos";

        public async Task<IActionResult> Index(Guid id)
        {
            Usuario usuario = new Usuario();
            usuario.AcessToken = HttpContext.Session.Get<String>("AcessToken");

            if (usuario.AcessToken == null)
            {
                ViewData["Error"] = "Para realizar uma compra é necessário logar no sistema!";
                return RedirectToAction("Login", "Usuarios");
            }

            Produtos produtos = new Produtos();

            using (var httpClient = new HttpClient())
            {
                httpClient.DefaultRequestHeaders.Add("Authorization", "Bearer " + usuario.AcessToken);

                using (var response = await httpClient.GetAsync(apiUrl + "/" + id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    produtos = JsonConvert.DeserializeObject<Produtos>(apiResponse);
                }
            }
            return View(produtos);
        }

        public async Task<IActionResult> Venda(Guid Id, Produtos produto)
        {
            Usuario usuario = new Usuario();
            usuario.Id = HttpContext.Session.Get<Guid>("Id");
            usuario.AcessToken = HttpContext.Session.Get<String>("AcessToken");

            Vendas venda = new Vendas();
            venda.ProdutoId = Id;
            venda.Data = DateTime.Now;
            venda.EmailComprador = HttpContext.Session.Get<String>("Email");

            produto.Ativo = false;


            //TODO: Acesso direto ao banco de dados
            //_context.Add(venda);
            //await _context.SaveChangesAsync();

            //TODO: Acesso API
            var json = JsonConvert.SerializeObject(venda);
            var jsonP = JsonConvert.SerializeObject(produto);

            var postRequest = new StringContent(json, Encoding.UTF8, "application/json");
            var postRequestP = new StringContent(jsonP, Encoding.UTF8, "application/json");

            using (var httpClient = new HttpClient())
            {
                httpClient.DefaultRequestHeaders.Add("Authorization", "Bearer " + usuario.AcessToken);


                using (var response = await httpClient.PutAsync(apiUrl + "/" + produto.Id, postRequestP))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                }

                using (var response = await httpClient.PostAsync(apiUrlv, postRequest).ConfigureAwait(true))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                }
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

NoPrecin/Views/Produtos/Criar.cshtml
@model NoPrecin.Models.Produtos

@{
    ViewData["Title"] = "CriarProduto";
}

<h1>Criar Produto</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Criar" asp-controller="Produtos" enctype="multipart/form-data" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagem" class="control-label"></label>
                <input type="file" name="arquivo" />
            </div>
            <div class="form-group">
                <label asp-for="Valor" class="control-label"></label>
                <input asp-for="Valor" class="form-control" />
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoProduto" class="control-label"></label>
                <select asp-for="TipoProduto" class="form-control" asp-items="Html.GetEnumSelectList<TipoProduto>()"></select>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Ativo" /> @Html.DisplayNameFor(model => model.Ativo)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

NoPrecin/Views/Produtos/Editar.cshtml
@model NoPrecin.Models.Produtos

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar</h1>

<h4>Produtos</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Editar">
            @Html.HiddenFor(x => x.DataCadastro)
            @Html.HiddenFor(x => x.Imagem)
            @Html.HiddenFor(x => x.Id)

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Valor" class="control-label"></label>
                <input asp-for="Valor" class="form-control" />
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoProduto" class="control-label"></label>
                <select asp-for="TipoProduto" class="form-control" asp-items="Html.GetEnumSelectList<TipoProduto>()"></select>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Ativo" /> @Html.DisplayNameFor(model => model.Ativo)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

NoPrecin/Views/Produtos/Index.cshtml
@model IEnumerable<NoPrecin.Models.Produtos>

@{
    ViewData["Title"] = "Index";
}

<h1>Todos os Produtos</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descricao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Valor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataCadastro)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TipoProduto)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (true)
        {
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Descricao)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Valor)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DataCadastro)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TipoProduto)
                    </td>

                    <td>
                        @Html.ActionLink("Comprar", "Index", "Vendas",  new { id = item.Id })
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td>
                    <b>Nenhum produto encontrado</b>
                </td>
                <td>
            </tr>
        }
    </tbody>
</table>

NoPrecin/Views/Produtos/ListarPorUsuario.cshtml
@model IEnumerable<NoPrecin.Models.Produtos>

@{
    ViewData["Title"] = "ListarPorUsuario";
}

<h1>Produtos Por Usuário</h1>

<p>
    <a asp-action="Criar">Novo Produto</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descricao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Valor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataCadastro)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TipoProduto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ativo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Vendido)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null)
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Descricao)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Valor)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DataCadastro)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TipoProduto)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Ativo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Vendido)
                    </td>
                    @if (item.Vendido == false)
                    {
                        <td>
                            @Html.ActionLink("Editar", "Editar", new { id = item.Id }) |
                            @Html.ActionLink("Deletar", "Deletar", new { id = item.Id })
                        </td>
                    }
                    else
                    {
                        <td></td>
                    }
                </tr>
            }
        }
        else
        {
            <tr>
                <td>
                    <b>Nenhum produto encontrado</b>
                </td>
                <td>
            </tr>
        }
    </tbody>
</table>

NoPrecin/Views/Produtos/MinhasCompras.cshtml
@model IEnumerable<NoPrecin.Models.Vendas>


@{
    Produtos produtos = new Produtos();
    ViewData["Title"] = "MinhasCompras";
}

<h1>Minhas Compras</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => produtos.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => produtos.Descricao)
            </th>
            <th>
                @Html.DisplayNameFor(model => produtos.Valor)
            </th>
            <th>
                @Html.DisplayName("Data Compra")
            </th>
            <th>
                @Html.DisplayNameFor(model => produtos.TipoProduto)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Count() > 0)
        {
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Produto.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Produto.Descricao)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Produto.Valor)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Data)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Produto.TipoProduto)
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td>
                    <b>Nenhuma compra efetuada</b>
                </td>
                <td>
            </tr>
        }
    </tbody>
</table>